### PR TITLE
remove expired sponsorship

### PR DESCRIPTION
**Pull request by fejes713**

### CODE REVIEW

**Comment by fejes713** [comment]
@Chalarangelo any idea why Travis fails?

**Comment by Chalarangelo** [comment]
It does all the time, I think I can fix it tomorrow morning.

**Comment by fejes713** [comment]
Should we merge it then or not?

**Comment by Chalarangelo** [comment]
@fejes713 I will merge it and change the Travis file right after to make it work (hopefully).

**Pull request merged**
